In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
%matplotlib inline

In [3]:
import pandas as pd
import numpy as np
import pickle

In [4]:
from fastai.nlp import *
from sklearn.linear_model import LogisticRegression

In [5]:
with open('processed_final_ws_hate', 'rb') as fp:
    data = pickle.load(fp)

In [6]:
data.head()

tweet  \
81624   I was advised earlier that such a redirect is ...   
75269   Please refrain from adding nonsense to Wikiped...   
19022   RT @fukkitsbrittney: @AustinBedsaul is so wise...   
80367                      You can post me messages here.   
111607                          On Southwest Airlines you   

                                              tweet_punct  \
81624   I was advised earlier that such a redirect is ...   
75269   Please refrain from adding nonsense to Wikiped...   
19022   RT fukkitsbrittney AustinBedsaul is so wise ye...   
80367                       You can post me messages here   
111607                          On Southwest Airlines you   

                                                tweet_pre  \
81624   advised earlier redirect desired option disamb...   
75269   please refrain adding nonsense wikipedia banan...   
19022   rt fukkitsbrittney austinbedsaul wise yet youn...   
80367                                       post messages   
111607                                 southwest airlines   

                                          tweet_tokenized  \
81624   [advised, earlier, redirect, desired, option, ...   
75269   [please, refrain, adding, nonsense, wikipedia,...   
19022   [rt, fukkitsbrittney, austinbedsaul, wise, yet...   
80367                                    [post, messages]   
111607                              [southwest, airlines]   

                                            tweet_nonstop  \
81624   [advised, earlier, redirect, desired, option, ...   
75269   [please, refrain, adding, nonsense, wikipedia,...   
19022   [rt, fukkitsbrittney, austinbedsaul, wise, yet...   
80367                                    [post, messages]   
111607                              [southwest, airlines]   

                                            tweet_stemmed  \
81624   [advis, earlier, redirect, desir, option, disa...   
75269   [pleas, refrain, ad, nonsens, wikipedia, banan...   
19022   [rt, fukkitsbrittney, austinbedsaul, wise, yet...   
80367                                      [post, messag]   
111607                                [southwest, airlin]   

                                         tweet_lemmatized  \
81624   [advised, earlier, redirect, desired, option, ...   
75269   [please, refrain, adding, nonsense, wikipedia,...   
19022   [rt, fukkitsbrittney, austinbedsaul, wise, yet...   
80367                                     [post, message]   
111607                               [southwest, airline]   

                                              tweet_clean  class  
81624   [advis, earlier, redirect, desir, option, disa...      0  
75269   [pleas, refrain, ad, nonsens, wikipedia, banan...      0  
19022   [rt, fukkitsbrittney, austinbedsaul, wise, yet...      1  
80367                                      [post, messag]      0  
111607                                [southwest, airlin]      0

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 199004 entries, 81624 to 14601
Data columns (total 9 columns):
tweet               199004 non-null object
tweet_punct         199004 non-null object
tweet_pre           199004 non-null object
tweet_tokenized     199004 non-null object
tweet_nonstop       199004 non-null object
tweet_stemmed       199004 non-null object
tweet_lemmatized    199004 non-null object
tweet_clean         199004 non-null object
class               199004 non-null int64
dtypes: int64(1), object(8)
memory usage: 15.2+ MB


In [8]:
data.shape

(199004, 9)

In [9]:
from sklearn.utils import shuffle
data = shuffle(data)
data.head()

tweet  \
112436  Joke \n\nI said nothing wrong, I was talking a...   
65966   these pictures are very old and are of not jat...   
32499   Just when you thought they couldn't possibly g...   
148983                           if it doesn't get lifted   
33201   User:They call me Mr. Pibb User:Saturation2 My...   

                                              tweet_punct  \
112436  Joke \n\nI said nothing wrong I was talking ab...   
65966   these pictures are very old and are of not jat...   
32499   Just when you thought they couldnt possibly ge...   
148983                            if it doesnt get lifted   
33201   UserThey call me Mr Pibb UserSaturation My con...   

                                                tweet_pre  \
112436  joke said nothing wrong talking posting real a...   
65966   pictures old jatts may low castes portraying j...   
32499                 thought couldnt possibly get dumber   
148983                                  doesnt get lifted   
33201   userthey call mr pibb usersaturation concern u...   

                                          tweet_tokenized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                            tweet_nonstop  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                            tweet_stemmed  \
112436  [joke, said, noth, wrong, talk, post, real, ar...   
65966   [pictur, old, jatt, may, low, cast, portray, j...   
32499            [thought, couldnt, possibl, get, dumber]   
148983                                [doesnt, get, lift]   
33201   [userthey, call, mr, pibb, usersatur, concern,...   

                                         tweet_lemmatized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [picture, old, jatts, may, low, caste, portray...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                              tweet_clean  class  
112436  [joke, said, noth, wrong, talk, post, real, ar...      0  
65966   [pictur, old, jatt, may, low, cast, portray, j...      0  
32499            [thought, couldnt, possibl, get, dumber]      1  
148983                                [doesnt, get, lift]      0  
33201   [userthey, call, mr, pibb, usersatur, concern,...      0

In [10]:
df = data['tweet']
df.head()

112436    Joke \n\nI said nothing wrong, I was talking a...
65966     these pictures are very old and are of not jat...
32499     Just when you thought they couldn't possibly g...
148983                             if it doesn't get lifted
33201     User:They call me Mr. Pibb User:Saturation2 My...
Name: tweet, dtype: object

In [13]:
y = data['class']
y.shape

(199004,)

In [14]:
def split_vals(a,n): return a[:n].copy(), a[n:].copy()

n_valid = 9004  
n_trn = len(df)-n_valid
raw_train, raw_valid = split_vals(data, n_trn)
X_train, X_valid = split_vals(df, n_trn)
y_train, y_valid = split_vals(y, n_trn)

X_train.shape, y_train.shape, X_valid.shape, y_valid.shape

((190000,), (190000,), (9004,), (9004,))

In [15]:
X_train.head()

112436    Joke \n\nI said nothing wrong, I was talking a...
65966     these pictures are very old and are of not jat...
32499     Just when you thought they couldn't possibly g...
148983                             if it doesn't get lifted
33201     User:They call me Mr. Pibb User:Saturation2 My...
Name: tweet, dtype: object

In [16]:
X_valid.head()

138766                    Re:Nonagenarians and Centenarians
13308             Niggas actin like hoes most of em bitches
112745                              go to hell you gestapo!
20983              So some pussy don't cream when they cum?
80290     What i believe is that you think you can contr...
Name: tweet, dtype: object

In [18]:
y_train.head()

112436    0
65966     0
32499     1
148983    0
33201     0
Name: class, dtype: int64

In [19]:
y_valid.head()

138766    0
13308     1
112745    1
20983     1
80290     0
Name: class, dtype: int64

# VECTOR CREATION

In [39]:
import sys
sys.setrecursionlimit(15000)

In [40]:
import nltk
stopword = nltk.corpus.stopwords.words('english')
ps = nltk.PorterStemmer()

In [41]:
def clean_text(text):
    text_lc = "".join([word.lower() for word in text if word not in string.punctuation]) # remove puntuation
    text_rc = re.sub('[0-9]+', '', text_lc)
    tokens = re.split('\W+', text_rc)    # tokenization
    text = [ps.stem(word) for word in tokens if word not in stopword]  # remove stopwords and stemming
    return text

In [42]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [43]:
v = CountVectorizer(analyzer=clean_text) 

In [44]:
v

CountVectorizer(analyzer=<function clean_text at 0x7efef9bade18>,
        binary=False, decode_error='strict', dtype=<class 'numpy.int64'>,
        encoding='utf-8', input='content', lowercase=True, max_df=1.0,
        max_features=None, min_df=1, ngram_range=(1, 1), preprocessor=None,
        stop_words=None, strip_accents=None,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, vocabulary=None)

In [45]:
trn = X_train
val = X_valid

In [46]:
trn_doc = v.fit_transform(trn)
val_doc = v.transform(val)

In [47]:
trn_doc

<190000x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 4443335 stored elements in Compressed Sparse Row format>

In [48]:
val_doc

<9004x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 203240 stored elements in Compressed Sparse Row format>

In [49]:
vocab = v.get_feature_names()

In [51]:
vocab[7000:7005]

['anom', 'anomal', 'anomali', 'anomeneprojector', 'anomi']

## NAIVE BAYES 

In [53]:
x = trn_doc
x

<190000x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 4443335 stored elements in Compressed Sparse Row format>

In [54]:
trn_y = y_train.to_numpy()
type(trn_y)

numpy.ndarray

In [56]:
trn_y.reshape(1, 190000)

array([[0, 0, 1, ..., 0, 0, 0]])

In [57]:
y = trn_y
y

array([0, 0, 1, ..., 0, 0, 0])

In [58]:
p = x[y==1].sum(0)+1
q = x[y==0].sum(0)+1

In [59]:
p

matrix([[9187,    1,    7, ...,    1,    1,    2]], dtype=int64)

In [60]:
p.shape

(1, 206367)

In [61]:
q

matrix([[104549,      5,     90, ...,      2,      2,     38]], dtype=int64)

In [62]:
q.shape

(1, 206367)

In [63]:
r = np.log((p/p.sum())/(q/q.sum()))

In [64]:
r

matrix([[-0.61524,  0.20719, -0.73727, ...,  1.12348,  1.12348, -1.12781]])

In [65]:
r.shape

(1, 206367)

In [66]:
b = np.log(len(p)/len(q))

In [67]:
b

0.0

In [72]:
val_y = y_valid.to_numpy()
type(val_y)

numpy.ndarray

In [73]:
val_y.shape

(9004,)

In [74]:
val_y.reshape(1, 9004)

array([[0, 1, 1, ..., 1, 0, 0]])

In [75]:
pre_preds = val_doc @ r.T + b
preds = pre_preds.T>0
(preds==val_y).mean()

0.9071523767214571

## LOGISTIC REGRESSION 

In [78]:
x

<190000x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 4443335 stored elements in Compressed Sparse Row format>

In [79]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [80]:
m = LogisticRegression(C=1e8, dual=True)
m.fit(x, y)
preds = m.predict(val_doc)
(preds==val_y).mean()

/home/spriyanshu723/anaconda3/envs/fastai-cpu/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/spriyanshu723/anaconda3/envs/fastai-cpu/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.9303642825410928

In [81]:
m = LogisticRegression(C=1e8, dual=True)
m.fit(trn_doc.sign(), y)
preds = m.predict(val_doc.sign())
(preds==val_y).mean()

/home/spriyanshu723/anaconda3/envs/fastai-cpu/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.9308085295424255

In [82]:
m = LogisticRegression(C=0.1, dual=True)
m.fit(trn_doc, y)
preds = m.predict(val_doc)
(preds==val_y).mean()

/home/spriyanshu723/anaconda3/envs/fastai-cpu/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


0.9419147045757441

In [83]:
m = LogisticRegression(C=0.1, dual=True)
m.fit(trn_doc.sign(), y)
preds = m.predict(val_doc.sign())
(preds==val_y).mean()

0.9424700133274101

## TRI-GRAM MODEL  

In [90]:
vec = CountVectorizer(ngram_range=(1,4), max_features=800000, analyzer=clean_text)

In [91]:
vec

CountVectorizer(analyzer=<function clean_text at 0x7efef9bade18>,
        binary=False, decode_error='strict', dtype=<class 'numpy.int64'>,
        encoding='utf-8', input='content', lowercase=True, max_df=1.0,
        max_features=800000, min_df=1, ngram_range=(1, 4),
        preprocessor=None, stop_words=None, strip_accents=None,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, vocabulary=None)

In [92]:
trn_doc = vec.fit_transform(trn)
val_doc = vec.transform(val)

In [93]:
trn_doc

<190000x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 4443335 stored elements in Compressed Sparse Row format>

In [94]:
val_doc

<9004x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 203240 stored elements in Compressed Sparse Row format>

In [95]:
vocab = vec.get_feature_names()

In [96]:
vocab[7000:7005]

['anom', 'anomal', 'anomali', 'anomeneprojector', 'anomi']

In [97]:
y = trn_y
y

array([0, 0, 1, ..., 0, 0, 0])

In [98]:
val_y

array([0, 1, 1, ..., 1, 0, 0])

In [99]:
x = trn_doc.sign()
x

<190000x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 4443335 stored elements in Compressed Sparse Row format>

In [100]:
val_x = val_doc.sign()
val_x

<9004x206367 sparse matrix of type '<class 'numpy.int64'>'
	with 203240 stored elements in Compressed Sparse Row format>

In [101]:
p = x[y==1].sum(0)+1
q = x[y==0].sum(0)+1
r = np.log((p/p.sum())/(q/q.sum()))
b = np.log(len(p)/len(q))

In [102]:
pre_preds = val_x @ r.T + b
preds = pre_preds.T>0
(preds==val_y).mean()

0.9045979564637938

In [103]:
m = LogisticRegression(C=0.1, dual=True)
m.fit(x,y)
preds = m.predict(val_x)
(preds==val_y).mean()

0.9424700133274101

In [104]:
r.shape

(1, 206367)

In [105]:
r

matrix([[-0.39889,  0.41648, -0.4102 , ...,  1.10963,  1.10963, -1.14166]])

In [106]:
np.exp(r)

matrix([[0.67106, 1.51662, 0.66352, ..., 3.03323, 3.03323, 0.31929]])

In [107]:
x_nb = x.multiply(r)
m = LogisticRegression(C=0.1, dual=True)
m.fit(x_nb,y)

val_x_nb = val_x.multiply(r)
preds = m.predict(val_x_nb)
(preds==val_y).mean()

0.9465792980897378

## FAST NBSVM++

In [108]:
sl = 10000

In [109]:
md = TextClassifierData.from_bow(trn_doc, trn_y, val_doc, val_y, sl)

In [110]:
md

In [111]:
learn = md.dotprod_nb_learner()

In [112]:
learn.fit(0.02, 1, wds=1e-6, cycle_len=1)

epoch      trn_loss   val_loss   <lambda>                       
    0      0.081596   0.091149   0.934085  



[array([0.09115]), 0.9340848511772546]

In [113]:
learn.fit(0.02, 1, wds=1e-6, cycle_len=1)

epoch      trn_loss   val_loss   <lambda>                       
    0      0.077287   0.079697   0.93775   



[array([0.0797]), 0.9377498889382496]

In [115]:
learn.fit(0.02, 1, wds=1e-6, cycle_len=1)

epoch      trn_loss   val_loss   <lambda>                       
    0      0.072299   0.076863   0.938638  


[array([0.07686]), 0.9386383829409152]

In [116]:
learn.fit(0.02, 1, wds=1e-6, cycle_len=1)

epoch      trn_loss   val_loss   <lambda>                       
    0      0.069775   0.075707   0.938972  


[array([0.07571]), 0.9389715681919147]

In [117]:
learn.fit(0.02, 1, wds=1e-6, cycle_len=1)

epoch      trn_loss   val_loss   <lambda>                       
    0      0.066827   0.074677   0.938972  


[array([0.07468]), 0.9389715681919147]

## TF-IDF 

In [118]:
data.head()

tweet  \
112436  Joke \n\nI said nothing wrong, I was talking a...   
65966   these pictures are very old and are of not jat...   
32499   Just when you thought they couldn't possibly g...   
148983                           if it doesn't get lifted   
33201   User:They call me Mr. Pibb User:Saturation2 My...   

                                              tweet_punct  \
112436  Joke \n\nI said nothing wrong I was talking ab...   
65966   these pictures are very old and are of not jat...   
32499   Just when you thought they couldnt possibly ge...   
148983                            if it doesnt get lifted   
33201   UserThey call me Mr Pibb UserSaturation My con...   

                                                tweet_pre  \
112436  joke said nothing wrong talking posting real a...   
65966   pictures old jatts may low castes portraying j...   
32499                 thought couldnt possibly get dumber   
148983                                  doesnt get lifted   
33201   userthey call mr pibb usersaturation concern u...   

                                          tweet_tokenized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                            tweet_nonstop  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                            tweet_stemmed  \
112436  [joke, said, noth, wrong, talk, post, real, ar...   
65966   [pictur, old, jatt, may, low, cast, portray, j...   
32499            [thought, couldnt, possibl, get, dumber]   
148983                                [doesnt, get, lift]   
33201   [userthey, call, mr, pibb, usersatur, concern,...   

                                         tweet_lemmatized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [picture, old, jatts, may, low, caste, portray...   
32499           [thought, couldnt, possibly, get, dumber]   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   

                                              tweet_clean  class  
112436  [joke, said, noth, wrong, talk, post, real, ar...      0  
65966   [pictur, old, jatt, may, low, cast, portray, j...      0  
32499            [thought, couldnt, possibl, get, dumber]      1  
148983                                [doesnt, get, lift]      0  
33201   [userthey, call, mr, pibb, usersatur, concern,...      0

In [121]:
data_hate = data.loc[data['class'] == 1]
data_hate.head()

tweet  \
32499   Just when you thought they couldn't possibly g...   
122304  Welcome back. Here is a crapping cat, a univer...   
2706    @Buckm00se all us beaners were pissed like rob...   
23196                  Yo main bitch that's my side hoe !   
2956             You are a raging faggot.  Kill yourself.   

                                              tweet_punct  \
32499   Just when you thought they couldnt possibly ge...   
122304  Welcome back Here is a crapping cat a universa...   
2706    Buckmse all us beaners were pissed like robert...   
23196                    Yo main bitch thats my side hoe    
2956               You are a raging faggot  Kill yourself   

                                                tweet_pre  \
32499                 thought couldnt possibly get dumber   
122304  welcome back crapping cat universal symbol rel...   
2706    buckmse us beaners pissed like robert jew ref ...   
23196                        yo main bitch thats side hoe   
2956                                   raging faggot kill   

                                          tweet_tokenized  \
32499           [thought, couldnt, possibly, get, dumber]   
122304  [welcome, back, crapping, cat, universal, symb...   
2706    [buckmse, us, beaners, pissed, like, robert, j...   
23196                 [yo, main, bitch, thats, side, hoe]   
2956                               [raging, faggot, kill]   

                                            tweet_nonstop  \
32499           [thought, couldnt, possibly, get, dumber]   
122304  [welcome, back, crapping, cat, universal, symb...   
2706    [buckmse, us, beaners, pissed, like, robert, j...   
23196                 [yo, main, bitch, thats, side, hoe]   
2956                               [raging, faggot, kill]   

                                            tweet_stemmed  \
32499            [thought, couldnt, possibl, get, dumber]   
122304  [welcom, back, crap, cat, univers, symbol, rel...   
2706    [buckms, us, beaner, piss, like, robert, jew, ...   
23196                  [yo, main, bitch, that, side, hoe]   
2956                                 [rage, faggot, kill]   

                                         tweet_lemmatized  \
32499           [thought, couldnt, possibly, get, dumber]   
122304  [welcome, back, crapping, cat, universal, symb...   
2706    [buckmse, u, beaner, pissed, like, robert, jew...   
23196                 [yo, main, bitch, thats, side, hoe]   
2956                               [raging, faggot, kill]   

                                              tweet_clean  class  
32499            [thought, couldnt, possibl, get, dumber]      1  
122304  [welcom, back, crap, cat, univers, symbol, rel...      1  
2706    [buckms, us, beaner, piss, like, robert, jew, ...      1  
23196                  [yo, main, bitch, that, side, hoe]      1  
2956                                 [rage, faggot, kill]      1

In [122]:
data.shape

(199004, 9)

In [123]:
data_hate.shape

(39090, 9)

In [124]:
data_unhate = data.loc[data['class'] == 0]
data_unhate.head()

tweet  \
112436  Joke \n\nI said nothing wrong, I was talking a...   
65966   these pictures are very old and are of not jat...   
148983                           if it doesn't get lifted   
33201   User:They call me Mr. Pibb User:Saturation2 My...   
104584  So it would be too difficult for you to write ...   

                                              tweet_punct  \
112436  Joke \n\nI said nothing wrong I was talking ab...   
65966   these pictures are very old and are of not jat...   
148983                            if it doesnt get lifted   
33201   UserThey call me Mr Pibb UserSaturation My con...   
104584  So it would be too difficult for you to write ...   

                                                tweet_pre  \
112436  joke said nothing wrong talking posting real a...   
65966   pictures old jatts may low castes portraying j...   
148983                                  doesnt get lifted   
33201   userthey call mr pibb usersaturation concern u...   
104584  would difficult write balanced article take ti...   

                                          tweet_tokenized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   
104584  [would, difficult, write, balanced, article, t...   

                                            tweet_nonstop  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [pictures, old, jatts, may, low, castes, portr...   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   
104584  [would, difficult, write, balanced, article, t...   

                                            tweet_stemmed  \
112436  [joke, said, noth, wrong, talk, post, real, ar...   
65966   [pictur, old, jatt, may, low, cast, portray, j...   
148983                                [doesnt, get, lift]   
33201   [userthey, call, mr, pibb, usersatur, concern,...   
104584  [would, difficult, write, balanc, articl, take...   

                                         tweet_lemmatized  \
112436  [joke, said, nothing, wrong, talking, posting,...   
65966   [picture, old, jatts, may, low, caste, portray...   
148983                              [doesnt, get, lifted]   
33201   [userthey, call, mr, pibb, usersaturation, con...   
104584  [would, difficult, write, balanced, article, t...   

                                              tweet_clean  class  
112436  [joke, said, noth, wrong, talk, post, real, ar...      0  
65966   [pictur, old, jatt, may, low, cast, portray, j...      0  
148983                                [doesnt, get, lift]      0  
33201   [userthey, call, mr, pibb, usersatur, concern,...      0  
104584  [would, difficult, write, balanc, articl, take...      0

In [125]:
data_unhate.shape

(159914, 9)

In [126]:
159914 + 39090

199004

## RETRIVING THE TOP WORDS FROM HATE DATASET 

In [161]:
hate_df = data_hate['tweet']
hate_df.head()

32499     Just when you thought they couldn't possibly g...
122304    Welcome back. Here is a crapping cat, a univer...
2706      @Buckm00se all us beaners were pissed like rob...
23196                    Yo main bitch that's my side hoe !
2956               You are a raging faggot.  Kill yourself.
Name: tweet, dtype: object

In [162]:
hate_df.shape

(39090,)

In [163]:
one = TfidfVectorizer(ngram_range=(1,4),
               min_df=3, max_df=0.9, strip_accents='unicode', use_idf=1,
               smooth_idf=1, sublinear_tf=1, tokenizer=tokenize)

In [164]:
one

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.9, max_features=None, min_df=3,
        ngram_range=(1, 4), norm='l2', preprocessor=None, smooth_idf=1,
        stop_words=None, strip_accents='unicode', sublinear_tf=1,
        token_pattern='(?u)\\b\\w\\w+\\b',
        tokenizer=<function tokenize at 0x7eff8e0279d8>, use_idf=1,
        vocabulary=None)

In [165]:
trn_term_doc = one.fit_transform(hate_df)

In [166]:
trn_term_doc

<39090x156376 sparse matrix of type '<class 'numpy.float64'>'
	with 2434763 stored elements in Compressed Sparse Row format>

In [167]:
indices_hate = np.argsort(one.idf_)[::-1]
features_hate = one.get_feature_names()
top_n = 1000
top_features_hate = [features_hate[i] for i in indices_hate[:top_n]]
print(top_features_hate)

[': " that \'', '? such', 'man , or', 'man , this', '? take a', 'man , you don', 'man , your', 'man . "', '? sure ,', 'man . i don', 'mama , bitch', "man . it '", 'man . the', '? stop being a', 'man @', 'man a', 'man ain', "man ain '", "man , it '", 'man , it', '? talk "', 'man , don', 'mama to', 'mama told', 'mama told me', 'mamas', '? that was a', 'man ! ! !', '? that makes', 'man " " ,', '? thanks for', '? thanks .', 'man & # 128514', 'man & # 8221', 'man , a', 'man , and', 'man , but', "man ain ' t", 'man and he', 'man ass', 'man lol', 'man on', 'man open', 'man open your', 'man open your curtains', 'man rt @', '? so i', "man that '", "man that ' s", 'man that bitch', 'man the', 'man them', 'man these hoes', 'man these hoes so', '? since you', 'man was a', 'man of', '? so what', 'man because', 'man just', '? stay', 'man cheated', 'man devoting', 'man devoting his', 'man devoting his life', 'man get', 'man http', 'man http :', 'man http : /', '? son of a', '? son of', '? someone who